### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by goddamnhippie** [mark-hahn/view-tail-large-files#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
new FilePicker (/Users/goddamnhippie/Code/dotfiles/source/atom/packages/view-tail-large-files/node_modules/vtlf-file-picker/lib/vtlf-file-picker.coffee:16:9)
```

**Comment by mark-hahn** [comment]
fixed in 0.1.9
