### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by asafyish** [mark-hahn/view-tail-large-files#11]
In keymaps/view-tail-large-files.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by mark-hahn** [comment]
FWIW, this is fixed.  I can't publish this package at this time because of https://github.com/atom/apm/issues/301.

**Comment by mark-hahn** [comment]
Fixed in 0.1.12
