### ISSUE TITLE
Behaviour when reaching beginning of a document using scrollbar

### ISSUE THREAD

**Issue by cascaval** [mark-hahn/view-tail-large-files#12]
If I open a large file, scroll down and then scroll back to the top of the file using the scrollbar, then:
* Text gets highlighted (not selected!) and it's not possible to get rid of this.
* It becomes impossible to use the scrollbar.

![screenshot from 2015-02-24 15 03 38](https://cloud.githubusercontent.com/assets/625419/6350832/67199fce-bc37-11e4-87c1-db1f435bc89c.png)

I don't observe this behaviour when using mouse scroll wheel or keyboard.

view-tail-large-files: 0.1.12
Atom: 0.182.0
OS: Ubuntu 14.04

**Comment by mark-hahn** [comment]
Thank you very much for the help.

Fixed in 0.1.13

**Comment by cascaval** [comment]
Thank you for creating the plugin and coming up with the fix.
