### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by santosborom** [mark-hahn/view-tail-large-files#20]
Are you trying to listen for the 'view-tail-large-files:up' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

**Comment by mark-hahn** [comment]
Hmmm.   I only have one key binding and it looks like ...

```
    @subs.add atom.commands.add 'atom-workspace, atom-text-editor::shadow', 'view-tail-large-files:open', =>
```
I can't run it because Atom won't load it.  I'll post an issue for this on Atom/Atom.

**Comment by mark-hahn** [comment]
See https://github.com/atom/atom/issues/7375.

**Comment by mark-hahn** [comment]
**This package is deprecated since Atom supports larger files now.  The tail functionality will be implemented in a new package by itself ASAP.**
