### ISSUE TITLE
If have a log file open and the file gets removed plugin throws error.

### ISSUE THREAD

**Issue by miketamis** [mark-hahn/view-tail-large-files#8]
Steps to Reproduce:
1. open file with view-tail-large-files
2. delete file externally, view error.

What should happen (IMO):
1. open file with view-tail-large-files
2. delete file externally, text view goes blank except first line is "File does exist"
3. recreate file, text view updates to show file.

why this effects me, when I run my program its first step is to delete/achrive the old log file, it then after a little bit creates a new one and starts to write to it. I would like it to not throw and error nor create an alert, but if i want to view the log tab, and the file is no existant it will tell me so.

**Comment by mark-hahn** [comment]
I just published version 1.0.7 to help with this problem.  Now when a file disappears the tab also disappears, which is what Atom normally does.  Then for 10 minutes it checks once a second to see if a file with the same path appears.  If it does then that new file is opened in a new tab.

Let me know if this works for you.  I couldn't give you exactly what you asked for without major changes.
